name: Default CI

on:
  push:
    branches:
      - '**'
      - '!master'
      - '!develop'
  pull_request:
    branches:
      - '**'
      - '!master'
      - '!develop'

jobs:
  linter:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: golangci-lint
        uses: golangci/golangci-lint-action@v2
        with:
          version: v1.40

  tests:
    runs-on: ubuntu-latest
    steps:
      - name: Install Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.15

      - name: Checkout code
        uses: actions/checkout@v2

      - name: Generate Swagger
        run: |
          go get github.com/swaggo/swag/cmd/swag
          swag init -g internal/app/app.go

      - name: Unit Tests
        run: go test --short -coverprofile=cover.out -v ./...
        env:
          GIN_MODE: release

      - name: Coverage
        run: go tool cover -func=cover.out

  build:
    runs-on: ubuntu-latest
    needs: tests

    steps:
      - name: Install Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.15

      - name: Checkout code
        uses: actions/checkout@v2

      - name: Generate Swagger
        run: |
          go get github.com/swaggo/swag/cmd/swag
          swag init -g internal/app/app.go

      - name: Build
        run: go build -ldflags="-w -s" -v -o main ./cmd/app/main.go
        env:
          GOOS: linux
          GOARCH: amd64
          CGO_ENABLED: 0

      - name: Upload Artifact
        uses: actions/upload-artifact@v2
        with:
          name: last-built-binary
          path: |
            main
            configs
          retention-days: 1
